services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped
    tty: true
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql-data:
