name: go

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: generate test coverage
        run: |
          go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
          go tool cover -html=cover.out -o=cover.html

      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          local-prefix: github.com/org/project
          threshold-file: 90
          threshold-package: 90
          threshold-total: 90

      - name: upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: cover.html
