name: go test

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout
        uses: actions/checkout@v4

      - name: Run setup-go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run go test
        run: go test -v ./...
