name: go

on:
  push:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-coverage:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - run: |
          go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
          go tool cover -html=cover.out -o=./docs/cover.html

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      - uses: actions/deploy-pages@v4
        id: deployment

      # - name: check test coverage
      #   uses: vladopajic/go-test-coverage@v2
      #   with:
      #     profile: cover.out
      #     local-prefix: github.com/org/project
      #     threshold-file: 90
      #     threshold-package: 90
      #     threshold-total: 90
